---
  api_key: ""
  token: ""

  list_actions_sensor:
    #api_key: ""
    #token: ""
    lists:
    - list_id: 55e7456df81e21e9b4aea429
      board_id: c39TEFLt
      #api_key: ""
      #token: ""

    - list_id: 55f95fc7f6352543770088be
      board_id: c39TEFLt
      filter:
        - updateCard
        - deleteCard
